
- uses: Platane/snk@master
  with:
   
    github_user_name: ${{ github.jasonprogrammer775}}

    # path of the generated gif file
    # If left empty, the gif file will not be generated
    gif_out_path: dist/github-snake.gif

    # path of the generated svg file
    # If left empty, the svg file will not be generated
    svg_out_path: dist/github-snake.svg
