name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: node.js 16
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@v3
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
