
 name: stack1
on:
    push:
        branches:
            - master

jobs:
    contrib-readme-job:
        runs-on: Node.js 16
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
        
              
              
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}








  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
